# Generated by Django 4.0.4 on 2022-04-22 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizes', '0002_alter_quizmodel_uuid_quizurlsmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizmodel',
            name='only_once',
        ),
        migrations.AlterField(
            model_name='questionmodel',
            name='type',
            field=models.CharField(choices=[('MW', 'Missing Word'), ('AN', 'Anagram'), ('GZ', 'GameShow Quiz')], default='GZ', max_length=2, verbose_name='Тип'),
        ),
    ]
