# Generated by Django 4.0.4 on 2022-04-22 22:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quizes', '0004_alter_answersmodel_question_alter_questionmodel_quiz_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompletedQuizModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student', models.CharField(max_length=64, verbose_name='Ф.И.О Студента: ')),
                ('email', models.EmailField(max_length=64, verbose_name='Email: ')),
                ('group', models.CharField(max_length=8, verbose_name='Группа: ')),
                ('result', models.CharField(max_length=32, verbose_name='Результат: ')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizes.quizmodel', verbose_name='Пройденый тест:')),
            ],
            options={
                'verbose_name': 'Отчет по тесту',
                'verbose_name_plural': 'Отчеты по тестам',
            },
        ),
    ]
