# Generated by Django 4.0.4 on 2022-04-23 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizes', '0005_completedquizmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizmodel',
            name='title',
            field=models.CharField(max_length=64, unique=True, verbose_name='Название теста'),
        ),
    ]
